[package]
name = "gdk-sys"
version = "0.1.0"
authors = [
    "guillaume1.gomez@gmail.com",
    "letang.jeremy@gmail.com",
    "mathijs.henquet@gmail.com",
    "bpgarman@fastmail.fm",
    "me@bstr.eu",
    "zsoakes@gmail.com",
    "Gleb Kozyrev <gleb@gkoz.com>",
]
build = "build.rs"
links = "gdk"

description = "FFI bindings to GDK"
repository = "https://github.com/jeremyletang/rgtk"
license = "MIT"

[lib]
name = "gdk_sys"

[dependencies]
bitflags = "0.1"
libc = "0.1"

[dependencies.glib-sys]
git = "https://github.com/rust-gnome/glib.git"

[build-dependencies]
pkg-config = "0.3"
